name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'

    - name: Build
      run: |
        yarn install
        yarn workspace @anticrm/platform build 
        yarn workspace @anticrm/platform-core build 
        yarn workspace @anticrm/platform-core-plugin build
        yarn workspace @anticrm/platform-core-model build

    - name: Test
      run: |
        yarn workspace @anticrm/platform run test
        yarn workspace @anticrm/platform-core-model run test
        yarn workspace @anticrm/platform-core-i18n run test
        yarn workspace @anticrm/platform-ui run test

    - name: Lint
      run: |
        yarn workspace @anticrm/platform run lint
        yarn workspace @anticrm/platform-core run lint
        yarn workspace @anticrm/platform-core-i18n run lint
        yarn workspace @anticrm/platform-ui run lint

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}   
      
    - name: Publish npms
      run: yarn workspace @anticrm/platform publish --access public --tag dev --no-commit-hooks --new-version 0.1.0-dev.${BUILD_NUMBER}
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    - name: Final
      run: |
        yarn workspace @anticrm/dev-boot run build
